### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/gambit#486]
**Updated 8/23/2016**
Update tests to remove code no longer used (#525, #542)

**Original description**
We repeatedly get the following error in our tests, which has been appearing and disappearing inexplicably:

```
error: uncaughtException: Cannot read property 'current_game_id' of null 
{ date: 'Wed Aug 12 2015 18:07:28 GMT+0000 (UTC)',
  process: 
   { pid: 1086,
     uid: 1000,
     gid: 1000,
     cwd: '/pipeline/build',
     execPath: '/usr/local/bin/node',
     version: 'v0.10.38',
     argv: 
      [ 'node',
        '/pipeline/build/node_modules/mocha/bin/_mocha',
        'test/_init.test.js',
        '-R',
        'spec' ],
     memoryUsage: 
      { rss: 124719104,
        heapTotal: 111824384,
        heapUsed: 57318304 } },
  os: 
   { loadavg: 
      [ 0.78955078125,
        0.27978515625,
        0.26953125 ],
     uptime: 6308415.718873266 },
  trace: 
   [ { column: 2800,
       file: '/pipeline/build/app/lib/sms-games/controllers/gameMessageHelpers.js',
       function: '',
       line: 9,
       method: null,
       native: false },
     { column: 8,
       file: '/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js',
       function: '',
       line: 177,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Promise.emit',
       line: 95,
       method: 'emit',
       native: false },
     { column: 38,
       file: '/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js',
       function: 'Promise.emit',
       line: 84,
       method: 'emit',
       native: false },
     { column: 20,
       file: '/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js',
       function: 'Promise.fulfill',
       line: 97,
       method: 'fulfill',
       native: false },
     { column: 30,
       file: '/pipeline/build/node_modules/mongoose/lib/query.js',
       function: 'Object.cb',
       line: 1153,
       method: 'cb',
       native: false },
     { column: 16,
       file: '/pipeline/build/node_modules/mongoose/node_modules/mquery/lib/utils.js',
       function: 'Object._onImmediate',
       line: 137,
       method: '_onImmediate',
       native: false },
     { column: 15,
       file: 'timers.js',
       function: 'processImmediate [as _immediateCallback]',
       line: 354,
       method: null,
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'current_game_id\' of null',
     '    at Promise.<anonymous> (/pipeline/build/app/lib/sms-games/controllers/gameMessageHelpers.js:9:2800)',
     '    at Promise.<anonymous> (/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)',
     '    at Promise.emit (events.js:95:17)',
     '    at Promise.emit (/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)',
     '    at Promise.fulfill (/pipeline/build/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)',
     '    at Object.cb (/pipeline/build/node_modules/mongoose/lib/query.js:1153:30)',
     '    at Object._onImmediate (/pipeline/build/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)',
     '    at processImmediate [as _immediateCallback] (timers.js:354:15)' ] }
```

This bug first showed up with [this wercker build](https://app.wercker.com/#buildstep/55b68c64f32b86a9293850d9). It reappears in many builds thereafter : 

https://app.wercker.com/#buildstep/55cb643bcb89a163160739e7
https://app.wercker.com/#buildstep/55cb69b6cb89a16316076e1e
https://app.wercker.com/#buildstep/55cb8b38d6c9772755034f8f

###Suspicions of what has caused this problem, which doesn't seem to show up on Tong's machine:

1. Node versioning differences (disproven)
2. MongoDB versioning differences (Tong's machine running on latest version of Mongo, where the problem doesn't show up; the problem showing up on Uy's machine, which does not have the latest version of Mongo; and uncertain if the problem shows up in production and if Compose is running the latest version of Mongo.

**Comment by aaronschachter** [comment]
I see this happen every time when I run `npm test`.

**Comment by aaronschachter** [comment]
Closing in favor of new coverage for new code #671
