### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'draft_reportback_submission' of undefined

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#972]
_BUG_
-------------------
#### Current Behavior
- We have an specific legacy bug. It happens when Northstar-js responds with `API response is false` to Campaigns when attempting to post a signup for an user. We suppress further Blink retries when we detect this error, under normal circumstances. Because of this bug, we are not telling Blink to stop retrying when this legacy bug occurs.
- `Unhandled rejection TypeError: Cannot read property 'draft_reportback_submission' of undefined` is triggered when a `renderEndConversationWithErrorMsg` reply is executed and the request is from Conversations.

```
2017-10-05T19:11:32.439203+00:00 app[web.1]: info: executing command: errorOccurred,[object Object]
2017-10-05T19:11:32.442208+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'draft_reportback_submission' of undefined
2017-10-05T19:11:32.442209+00:00 app[web.1]:     at formatSignupResponse (/app/lib/helpers.js:264:29)
2017-10-05T19:11:32.442210+00:00 app[web.1]:     at Object.module.exports.sendResponseForSignup (/app/lib/helpers.js:303:13)
2017-10-05T19:11:32.442210+00:00 app[web.1]:     at Command.execute (/app/lib/conversation/replies.js:75:22)
2017-10-05T19:11:32.442211+00:00 app[web.1]:     at Function.execute (/app/lib/conversation/reply-dispatcher.js:9:20)
2017-10-05T19:11:32.442211+00:00 app[web.1]:     at Object.handlePhoenixPostError (/app/lib/helpers.js:22:28)
2017-10-05T19:11:32.442212+00:00 app[web.1]:     at Signup.post.then.catch.err (/app/lib/middleware/signup-create.js:19:29)
2017-10-05T19:11:32.442212+00:00 app[web.1]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-10-05T19:11:32.442215+00:00 app[web.1]:     at Promise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
2017-10-05T19:11:32.442215+00:00 app[web.1]:     at Promise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-10-05T19:11:32.442216+00:00 app[web.1]:     at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:471:26)
2017-10-05T19:11:32.442216+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2017-10-05T19:11:32.442217+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2017-10-05T19:11:32.442217+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2017-10-05T19:11:32.442218+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2017-10-05T19:11:32.442218+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
2017-10-05T19:11:32.442218+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
2017-10-05T19:11:32.442219+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2017-10-05T19:11:32.442219+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
2017-10-05T19:11:32.442220+00:00 app[web.1]:     at Immediate.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-10-05T19:11:32.442221+00:00 app[web.1]:     at runCallback (timers.js:672:20)
2017-10-05T19:11:32.442221+00:00 app[web.1]:     at tryOnImmediate (timers.js:645:5)
2017-10-05T19:11:32.442221+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

#### Desired Behavior
- Should respond back with error to Conversations when it sends an `errorOcurred` reply.

#### Why This Matters
When enough of these happen, it hangups the Heroku Dyno and eventually all requests get the 503 H12 error.

#### Related Issues
It's worth it to look up for Uncaught Exceptions that may be causing #961.

**Comment by rapala61** [comment]
@DFurnes would implementing #970 remove the headache of this "legacy" bug?

**Comment by sergii-tkachenko** [comment]
Yes, we noticed this bug too when were testing Gambit at "Gimlets and Gambit". Here's what I've seen in Blink:

```
response_status_text="Internal Server Error" {"message":"req.campaign.templates.errorOccurred undefined"}
```

Message Example:
```
{
    "ToCountry": "US",
    "ToState": "FL",
    "SmsMessageSid": "SM50e7e6a49a066653afbc751d5fa140ff",
    "NumMedia": "0",
    "ToCity": "MIAMI",
    "FromZip": "22209",
    "SmsSid": "SM50e7e6a49a066653afbc751d5fa140ff",
    "FromState": "DC",
    "SmsStatus": "received",
    "FromCity": "WASHINGTON",
    "Body": "This is a text 🦂",
    "FromCountry": "US",
    "To": "+1305CENSORED",
    "MessagingServiceSid": "MGd8b9511cf6b463b673a6ce660a08ef3d",
    "ToZip": "33016",
    "NumSegments": "1",
    "MessageSid": "SM50e7e6a49a066653afbc751d5fa140ff",
    "AccountSid": "AC54a6683e7e5a2232aa9679003e84a685",
    "From": "+1202CENSORED",
    "ApiVersion": "2010-04-01"
  }
```

**Comment by sergii-tkachenko** [comment]
Not related to the emoji BTW>
